# site settings
title: Akash R. Chaurasia
subtitle: 
email: akashc@jhu.edu
description: A website to showcase projects & my life
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akashc1.github.io"# the base hostname & protocol for your site
author: Akash Chaurasia
city: Baltimore
state: MD
country: United States of America

# homepage tiles
tiles-source: _pages # accepts "posts" or "pages"
tiles-count: 6

image: assets/images/pic02.jpg

# social settings
500px_url:
facebook_url: https://www.facebook.com/akash.chaurasia.75
github_url: https://github.com/akashc1
gitlab_url: https://gitlab.com/u/achaura1
instagram_url: https://instagram.com/kashiomoney
linkedin_url: https://www.linkedin.com/in/akashchaurasia

# build settings
markdown: kramdown

sass:
  style: compressed
